create or replace procedure BAD_DATA_PROCEDURE
as
begin
  FOR source IN (SELECT * FROM STAGING_COMPLAINT where DESCRIPTION is null and COMPLAINT_STATUS='open' ) LOOP
   INSERT INTO BAD_COMPLAINT(BAD_COMPLAINT_ID,COMPLAINT_ID,COMPLAINT_TYPE,DESCRIPTION,COMPLAINT_STATUS,COMPENSATION_AMNT,COMPENSATION_TYPE,FK1_CUSTOMER_ID,ERROR_DESCRIPTION,RESOLUTION_DATE,STATUS, YEAR, MONTH,DAY)
   VALUES(BAD_COMPLAINTS_SEQ.nextval,source.COMPLAINT_ID,source.COMPLAINT_TYPE,source.DESCRIPTION,source.COMPLAINT_STATUS,source.COMPENSATION_AMNT,source.COMPENSATION_TYPE,source.FK1_CUSTOMER_ID,'DESCRIPTION MISSING',sysdate,'issue',source.YEAR,source.MONTH,SOURCE.DAY);
END LOOP;
END;
