create or replace procedure BAD_flight_PROCEDURE
as
begin
  FOR source IN (SELECT * FROM STAGING_FLIGHTS where tail_number is null OR arrival_delay is null OR departure_delay is null OR cancelled is null ) LOOP
   INSERT INTO BAD_FLIGHTS(BAD_FLIGHT_ID,FLIGHT_ID,YEAR,MONTH,DAY,TAIL_NUMBER,FLIGHT_NUMBER,ORIGIN_AIRPORT,ARRIVAL_DELAY,DESTINATION_AIRPORT,DEPARTURE_DELAY,CANCELLED,CANCELLED_REASON,DATA_SOURCE,ERROR_DESCRIPTION,RESOLUTION_DATE)
   VALUES(BAD_FLIGHTS_SEQ.nextval,source.FLIGHT_ID,source.YEAR,source.MONTH,source.DAY, source.TAIL_NUMBER,source.FLIGHT_NUMBER,source.ORIGIN_AIRPORT,source.ARRIVAL_DELAY,source.DESTINATION_AIRPORT,source.departure_delay,source.CANCELLED,source.CANCELLED_REASON,source.DATA_SOURCE,'VALUES MISSING',sysdate);
END LOOP;
END;
